social_Media/simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
url(r'^signup/$',views.SignUp.as_view(),name='signup'),
]

social_Media/simplesocial/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

social_Media/simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

social_Media/simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
	<title>Social Site</title>
	<!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

</head>
<body>
	<nav class="navbar navbar-default" role='navigation' id='navbar'>
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}"><i class="fas fa-feather-alt"> Star Social</a>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="{% url 'posts:create' %}">Post</a></li>
                <li><a href="{% url 'groups:all' %}">Groups</a></li>
                <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                
                {% else %}
                <li><a href="{% url 'groups:all' %}">Groups</a></li>
                <li><a href="{% url 'accounts:login' %}"><i class="fas fa-sign-in-alt"> Login</a></li>
                <li><a href="{% url 'accounts:signup' %}"><i class="fas fa-user-plus"> Sign Up</a></li>
                </ul>
                {% endif %}
        </div>
	</nav>
{% block content %}
<div class="container mycontent">
    
</div>
{% endblock %}
<canvas id="canvas"></canvas>
</body>
<script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}"></script>
</html>

social_Media/simplesocial/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text">Welcome to Star Social!</h1>
{% endblock %}

social_Media/simplesocial/templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text">You are now logged in!</h1>
{% endblock %}

social_Media/simplesocial/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text">Thanks for visiting, come back soon!</h1>
{% endblock %}